import { StrokeProfile } from '../geometry/StrokeGeometryBuilder';
import { MaterialType } from '../shaders/CustomShaderMaterials';

export type BrushCategory =
  | 'all'
  | 'starter'
  | 'basics'
  | 'paints'
  | 'markers'
  | 'hair'
  | 'fx'
  | 'nature'
  | 'smear'
  | 'animated'
  | 'custom';

export const STARTER_BRUSH_IDS: string[] = [
  'rainbow_streak',
  'glow_neon',
  'stardust_splatter',
  'fire_magic',
  'paint_splatter',
  'round_acrylic',
  'pencil_hb',
  'felt_pen',
];

export interface BrushPreset {
  id: string;
  name: string;
  category: BrushCategory;
  description: string;
  profile: StrokeProfile;
  materialType: MaterialType;
  defaultSize: number;
  defaultOpacity: number;
  smoothingAlpha: number;
  taperStart: boolean;
  taperEnd: boolean;
  pressureRadius: boolean;
  pressureOpacity: boolean;
  colorHex?: string;
  iconFile?: string;
  svgPath?: string;
}

export interface BrushCategoryInfo {
  id: BrushCategory;
  name: string;
  description: string;
}

export const BRUSH_CATEGORIES: BrushCategoryInfo[] = [
  { id: 'starter', name: 'Starter', description: 'Fun brushes to get started — rainbow, glow, stardust & more' },
  { id: 'all', name: 'All Brushes', description: 'Complete brush collection' },
  { id: 'basics', name: 'Pencils & Pens', description: 'Graphite pencils, technical inking & fine pens' },
  { id: 'paints', name: 'Acrylics & Oils', description: 'Wet media, loaded bristle rakes & impasto' },
  { id: 'markers', name: 'Markers & Inks', description: 'Copic chisel markers, highlighters & felt pens' },
  { id: 'hair', name: 'Hair & Curls', description: '3D afro coils, curly waves, crimp & hair rakes' },
  { id: 'fx', name: 'FX & Textures', description: 'Neon glow, rainbow streaks, stardust & halftones' },
  { id: 'nature', name: 'Nature & Leaves', description: 'Maple, oak, fir needles & foliage bunches' },
  { id: 'smear', name: 'Smudge & Blend', description: 'Soft smear, fan blend & textured smudging' },
  { id: 'animated', name: 'Animated & Magic', description: 'Water effects, rainbow, sparkle, lava & galaxy animated strokes' },
  { id: 'custom', name: 'Custom Presets', description: 'User saved brush configurations' }
];

export const BRUSH_PRESETS: Record<string, BrushPreset> = {
  // -------------------------------------------------------------
  // 1. BASICS & PENCILS
  // -------------------------------------------------------------
  pencil_hb: {
    id: 'pencil_hb',
    name: 'HB Sketch Pencil',
    category: 'basics',
    description: 'Fine graphite sketch pencil with paper grain texture',
    profile: 'ribbon',
    materialType: 'pencil',
    defaultSize: 0.015,
    defaultOpacity: 0.85,
    smoothingAlpha: 0.45,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#3a3a48',
    iconFile: 'pencil_hb.png'
  },
  pencil_4b: {
    id: 'pencil_4b',
    name: '4B Soft Pencil',
    category: 'basics',
    description: 'Rich dark graphite lead for shading and broad gestures',
    profile: 'ribbon',
    materialType: 'pencil',
    defaultSize: 0.030,
    defaultOpacity: 0.95,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#252530',
    iconFile: 'pencil_4b.png'
  },
  technical_pen: {
    id: 'technical_pen',
    name: 'Technical Pen',
    category: 'basics',
    description: 'Precise uniform inking pen with high stabilization',
    profile: 'ribbon',
    materialType: 'shadeless',
    defaultSize: 0.008,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.50,
    taperStart: false,
    taperEnd: false,
    pressureRadius: false,
    pressureOpacity: false,
    colorHex: '#111118',
    iconFile: 'technical-pen-icon.png'
  },
  fountain_pen: {
    id: 'fountain_pen',
    name: 'Fountain Pen',
    category: 'basics',
    description: 'Classic inking pen with responsive taper and line weight',
    profile: 'ribbon',
    materialType: 'shadeless',
    defaultSize: 0.016,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.45,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#181824',
    iconFile: 'inkingpen.png'
  },
  ballpoint: {
    id: 'ballpoint',
    name: 'Ballpoint Pen',
    category: 'basics',
    description: 'Everyday smooth ballpoint with gentle pressure shading',
    profile: 'tube',
    materialType: 'shaded',
    defaultSize: 0.012,
    defaultOpacity: 0.90,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#1f2e66',
    iconFile: 'ball_point_pen.png'
  },
  calligraphy: {
    id: 'calligraphy',
    name: 'Calligraphy Chisel',
    category: 'basics',
    description: 'Angled calligraphic chisel blade for varied stroke widths',
    profile: 'chisel',
    materialType: 'shadeless',
    defaultSize: 0.040,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#1a1a2e',
    iconFile: 'chisel_tip.png'
  },
  charcoal_grain: {
    id: 'charcoal_grain',
    name: 'Traditional Charcoal',
    category: 'basics',
    description: 'Rough vine charcoal stick with intense tooth and grain',
    profile: 'ribbon',
    materialType: 'pencil',
    defaultSize: 0.045,
    defaultOpacity: 0.90,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#1c1c1c',
    iconFile: 'charcoal.png'
  },
  fine_art_ink: {
    id: 'fine_art_ink',
    name: 'Fine Art Ink Brush',
    category: 'basics',
    description: 'Supple calligraphy ink brush with expressive dynamic flow',
    profile: 'chisel',
    materialType: 'shadeless',
    defaultSize: 0.035,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.45,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#0f0f14',
    iconFile: 'Ink Brush.png'
  },

  // -------------------------------------------------------------
  // 2. PAINTS & ACRYLICS
  // -------------------------------------------------------------
  round_acrylic: {
    id: 'round_acrylic',
    name: 'Basic Round Acrylic',
    category: 'paints',
    description: 'Smooth full-bodied 3D acrylic stroke with natural sheen',
    profile: 'tube',
    materialType: 'shaded',
    defaultSize: 0.045,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#800040',
    iconFile: 'paintbrush1.png'
  },
  flat_acrylic: {
    id: 'flat_acrylic',
    name: 'Small Flat Acrylic',
    category: 'paints',
    description: 'Crisp flat acrylic brush for blocking shapes and edges',
    profile: 'ribbon',
    materialType: 'acrylic',
    defaultSize: 0.035,
    defaultOpacity: 0.95,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#006666',
    iconFile: 'palette_flat_brush3.png'
  },
  loaded_square: {
    id: 'loaded_square',
    name: 'Loaded Square Acrylic',
    category: 'paints',
    description: 'Heavy loaded acrylic paint stroke with viscous body',
    profile: 'ribbon',
    materialType: 'acrylic',
    defaultSize: 0.065,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#225533',
    iconFile: 'palette_heavy_flat_brush2.png'
  },
  wet_acrylic: {
    id: 'wet_acrylic',
    name: 'Wet Square Acrylic',
    category: 'paints',
    description: 'Wet blendable acrylic paint with soft translucent edges',
    profile: 'ribbon',
    materialType: 'watercolor',
    defaultSize: 0.050,
    defaultOpacity: 0.70,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#1a4466',
    iconFile: 'palette_soft_flat_brush.png'
  },
  rake_acrylic: {
    id: 'rake_acrylic',
    name: 'Rake Acrylic Bristle',
    category: 'paints',
    description: 'Multi-strand parallel bristle rake for painterly texture',
    profile: 'bristle',
    materialType: 'acrylic',
    defaultSize: 0.070,
    defaultOpacity: 0.90,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#552244',
    iconFile: 'palette_flat_bristle_brush2.png'
  },
  watercolor_wash: {
    id: 'watercolor_wash',
    name: 'Watercolor Wash',
    category: 'paints',
    description: 'Soft translucent organic wash with pigment puddle edge',
    profile: 'ribbon',
    materialType: 'watercolor',
    defaultSize: 0.080,
    defaultOpacity: 0.45,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#336699',
    iconFile: 'Wash.png'
  },
  salty_watercolor: {
    id: 'salty_watercolor',
    name: 'Salty Watercolor',
    category: 'paints',
    description: 'Granulating watercolor wash with pigment pooling and granulation',
    profile: 'ribbon',
    materialType: 'watercolor',
    defaultSize: 0.075,
    defaultOpacity: 0.55,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#2b5876',
    iconFile: 'Salty Watercolor.png'
  },
  bleeding_watercolor: {
    id: 'bleeding_watercolor',
    name: 'Bleeding Watercolor',
    category: 'paints',
    description: 'Heavy diffusion wet-on-wet watercolor with organic bleeding',
    profile: 'ribbon',
    materialType: 'watercolor',
    defaultSize: 0.085,
    defaultOpacity: 0.50,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#4e4376',
    iconFile: 'Bleeding Watercolor.png'
  },
  synthetic_round_bristle: {
    id: 'synthetic_round_bristle',
    name: 'Synthetic Round Bristle',
    category: 'paints',
    description: 'High-res synthetic round paint brush with responsive spring',
    profile: 'bristle',
    materialType: 'acrylic',
    defaultSize: 0.060,
    defaultOpacity: 0.85,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#c0392b',
    iconFile: 'Synthetic Round Bristle.png'
  },
  oil_impasto: {
    id: 'oil_impasto',
    name: 'Oil Impasto 3D',
    category: 'paints',
    description: 'Sculpted 3D tube with high specular lighting and volume',
    profile: 'tube',
    materialType: 'cel_shaded',
    defaultSize: 0.055,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#aa4400',
    iconFile: 'paintbrush2.png'
  },

  // -------------------------------------------------------------
  // 3. MARKERS & INKS
  // -------------------------------------------------------------
  copic_marker: {
    id: 'copic_marker',
    name: 'Copic Art Marker',
    category: 'markers',
    description: 'Alcohol art marker with chisel tip and multiplying ink',
    profile: 'chisel',
    materialType: 'marker',
    defaultSize: 0.060,
    defaultOpacity: 0.65,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#008080',
    iconFile: 'palette_marker.png'
  },
  highlighter: {
    id: 'highlighter',
    name: 'Neon Highlighter',
    category: 'markers',
    description: 'Vibrant flat fluorescent marker with high transparency',
    profile: 'chisel',
    materialType: 'marker',
    defaultSize: 0.075,
    defaultOpacity: 0.45,
    smoothingAlpha: 0.35,
    taperStart: false,
    taperEnd: false,
    pressureRadius: false,
    pressureOpacity: false,
    colorHex: '#ffee00',
    iconFile: 'marker_large.png'
  },
  felt_pen: {
    id: 'felt_pen',
    name: 'Felt Marker Pen',
    category: 'markers',
    description: 'Bold solid felt marker for concept art and outlines',
    profile: 'ribbon',
    materialType: 'shadeless',
    defaultSize: 0.025,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#0a0a14',
    iconFile: 'felt_pen.png'
  },
  fine_line: {
    id: 'fine_line',
    name: 'Fine Liner 0.5mm',
    category: 'markers',
    description: 'Ultra thin architectural fineliner for precision lines',
    profile: 'ribbon',
    materialType: 'shadeless',
    defaultSize: 0.007,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.45,
    taperStart: false,
    taperEnd: false,
    pressureRadius: false,
    pressureOpacity: false,
    colorHex: '#000000',
    iconFile: 'Fineline Pen.png'
  },

  // -------------------------------------------------------------
  // 4. HAIR, COILS & WAVES
  // -------------------------------------------------------------
  hair_tight_coils: {
    id: 'hair_tight_coils',
    name: 'Tight Afro Coils',
    category: 'hair',
    description: '3D high-frequency spiral helical coil for afro & textured hair',
    profile: 'hair_coil',
    materialType: 'shaded',
    defaultSize: 0.030,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#1c140d',
    iconFile: 'Hair.png'
  },
  hair_loose_curls: {
    id: 'hair_loose_curls',
    name: 'Loose Wavy Curls',
    category: 'hair',
    description: 'Smooth undulating 3D spiral curls for wavy locks',
    profile: 'hair_wave',
    materialType: 'shaded',
    defaultSize: 0.035,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#3b2219',
    iconFile: 'Hair.png'
  },
  hair_zigzag: {
    id: 'hair_zigzag',
    name: 'Zig-Zag Crimped Hair',
    category: 'hair',
    description: 'Angular crimped zigzag hair path with dynamic energy',
    profile: 'hair_zigzag',
    materialType: 'shaded',
    defaultSize: 0.028,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#261710',
    iconFile: 'fibre.png'
  },
  hair_multi_strand: {
    id: 'hair_multi_strand',
    name: 'Multi-Strand Hair Rake',
    category: 'hair',
    description: 'Parallel individual hair fiber strokes for quick locks',
    profile: 'bristle',
    materialType: 'shaded',
    defaultSize: 0.050,
    defaultOpacity: 0.95,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#4a2e1b',
    iconFile: 'palette_flat_bristle_brush.png'
  },
  hair_braid: {
    id: 'hair_braid',
    name: 'Braided Strand',
    category: 'hair',
    description: 'Woven ribbon braid with smooth shaded form',
    profile: 'ribbon',
    materialType: 'shaded',
    defaultSize: 0.040,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#593822',
    iconFile: 'spline_1.png'
  },

  // -------------------------------------------------------------
  // 5. FX & TEXTURES (FY BRUSH SET)
  // -------------------------------------------------------------
  glow_neon: {
    id: 'glow_neon',
    name: 'Neon Glow Tube',
    category: 'fx',
    description: 'Radiant emissive neon light beam with bloom halo',
    profile: 'tube',
    materialType: 'glow',
    defaultSize: 0.035,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#00ffcc',
    iconFile: 'glowneon.png'
  },
  glow_wispy: {
    id: 'glow_wispy',
    name: 'Glow Wispy Strand',
    category: 'fx',
    description: 'Tapered glowing wispy light filament for ethereal effects',
    profile: 'ribbon',
    materialType: 'glow',
    defaultSize: 0.030,
    defaultOpacity: 0.85,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#00e5ff',
    iconFile: 'glowwispy.png'
  },
  rainbow_streak: {
    id: 'rainbow_streak',
    name: 'Rainbow Spectrum',
    category: 'fx',
    description: 'Continuous shifting rainbow color gradient along stroke',
    profile: 'ribbon',
    materialType: 'rainbow',
    defaultSize: 0.045,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ff3366',
    iconFile: 'glowbrush.png'
  },
  stardust_splatter: {
    id: 'stardust_splatter',
    name: 'Stardust & Splatter',
    category: 'fx',
    description: 'Scattered glittering particle specks and cosmic stardust',
    profile: 'particles',
    materialType: 'stardust',
    defaultSize: 0.055,
    defaultOpacity: 0.90,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ffd700',
    iconFile: 'sparkle.png'
  },
  cloud_nebula: {
    id: 'cloud_nebula',
    name: 'Cloud & Nebula',
    category: 'fx',
    description: 'Soft billowy volumetric cloud clusters and space nebulae',
    profile: 'particles',
    materialType: 'glow',
    defaultSize: 0.085,
    defaultOpacity: 0.40,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#9966ff',
    iconFile: 'blurry.png'
  },
  bokeh_dots: {
    id: 'bokeh_dots',
    name: 'Bokeh Light Orbs',
    category: 'fx',
    description: 'Cinematic glowing circular bokeh bubbles and orbs',
    profile: 'particles',
    materialType: 'glow',
    defaultSize: 0.065,
    defaultOpacity: 0.55,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ff66aa',
    iconFile: 'dotted_3.png'
  },
  fire_magic: {
    id: 'fire_magic',
    name: 'Fire & Magic Ribbon',
    category: 'fx',
    description: 'Fiery glowing trail with intense emissive core',
    profile: 'ribbon',
    materialType: 'glow',
    defaultSize: 0.040,
    defaultOpacity: 0.95,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ff4400',
    iconFile: 'Wispy.png'
  },
  paint_splatter: {
    id: 'paint_splatter',
    name: 'Dynamic Paint Splatter',
    category: 'fx',
    description: 'Chaotic multi-scale paint drops and mist bursts',
    profile: 'particles',
    materialType: 'stardust',
    defaultSize: 0.065,
    defaultOpacity: 0.80,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#e91e63',
    iconFile: 'paint_splatter_1.png'
  },
  dream_brush: {
    id: 'dream_brush',
    name: 'Dream Brush Soft',
    category: 'fx',
    description: 'Soft dreamy atmospheric texture brush for lighting and mist',
    profile: 'particles',
    materialType: 'glow',
    defaultSize: 0.090,
    defaultOpacity: 0.35,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#9c27b0',
    iconFile: 'Dream Brush.png'
  },
  halftone_dots: {
    id: 'halftone_dots',
    name: 'Halftone Screen',
    category: 'fx',
    description: 'Retro comic print halftone dot matrix pattern',
    profile: 'ribbon',
    materialType: 'halftone',
    defaultSize: 0.055,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#000000',
    iconFile: 'half-tone-dot-pattern1-icon.png'
  },
  crosshatch_pen: {
    id: 'crosshatch_pen',
    name: 'Crosshatch Shading',
    category: 'fx',
    description: 'Procedural engraving crosshatch texture for shadows',
    profile: 'ribbon',
    materialType: 'crosshatch',
    defaultSize: 0.045,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#222233',
    iconFile: 'hatch.png'
  },
  stipple_dots: {
    id: 'stipple_dots',
    name: 'Stipple Shading',
    category: 'fx',
    description: 'Fine dot stippling for soft pointillism shading',
    profile: 'ribbon',
    materialType: 'stipple',
    defaultSize: 0.050,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#111122',
    iconFile: 'dotted_1.png'
  },

  // -------------------------------------------------------------
  // 6. NATURE & FOLIAGE
  // -------------------------------------------------------------
  foliage_maple: {
    id: 'foliage_maple',
    name: 'Maple Leaves',
    category: 'nature',
    description: 'Scattered autumn maple leaves with natural rotation',
    profile: 'foliage',
    materialType: 'foliage_leaf',
    defaultSize: 0.055,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#d94411',
    iconFile: 'anemone_2.png'
  },
  foliage_oak: {
    id: 'foliage_oak',
    name: 'Oak Leaves',
    category: 'nature',
    description: 'Lobed green oak leaves along branch paths',
    profile: 'foliage',
    materialType: 'foliage_leaf',
    defaultSize: 0.050,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#2d6a4f',
    iconFile: 'abstract_1.png'
  },
  foliage_beech: {
    id: 'foliage_beech',
    name: 'Beech Leaves',
    category: 'nature',
    description: 'Bright oval deciduous beech leaves',
    profile: 'foliage',
    materialType: 'foliage_leaf',
    defaultSize: 0.045,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#70e000',
    iconFile: 'abstract_2.png'
  },
  foliage_fir: {
    id: 'foliage_fir',
    name: 'Fir Evergreen Needles',
    category: 'nature',
    description: 'Dense spruce and pine needles radiating along branches',
    profile: 'foliage',
    materialType: 'foliage_fir',
    defaultSize: 0.050,
    defaultOpacity: 0.90,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#1b4332',
    iconFile: 'thorny.png'
  },
  foliage_bunch: {
    id: 'foliage_bunch',
    name: 'Leaf Bunch Canopy',
    category: 'nature',
    description: 'Dense clustered leaf canopy for bushes and trees',
    profile: 'foliage',
    materialType: 'foliage_leaf',
    defaultSize: 0.075,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.30,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#38b000',
    iconFile: 'camo.png'
  },
  grass_tuft: {
    id: 'grass_tuft',
    name: 'Grass Blades & Vines',
    category: 'nature',
    description: 'Tapered organic grass blades and climbing vines',
    profile: 'ribbon',
    materialType: 'cel_shaded',
    defaultSize: 0.022,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#52b788',
    iconFile: 'spline_02.png'
  },

  // -------------------------------------------------------------
  // 7. SMEAR & BLENDING
  // -------------------------------------------------------------
  soft_smear: {
    id: 'soft_smear',
    name: 'Soft Smear Brush',
    category: 'smear',
    description: 'Feathered soft smudge for smooth gradient blending',
    profile: 'ribbon',
    materialType: 'watercolor',
    defaultSize: 0.065,
    defaultOpacity: 0.40,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#888888',
    iconFile: 'palette_smear.png'
  },
  fan_smear: {
    id: 'fan_smear',
    name: 'Smear Fan Brush',
    category: 'smear',
    description: 'Broad fan brush spread for sweeping color transitions',
    profile: 'bristle',
    materialType: 'watercolor',
    defaultSize: 0.085,
    defaultOpacity: 0.35,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#666666',
    iconFile: 'palette_fan_brush.png'
  },
  square_smear: {
    id: 'square_smear',
    name: 'Smear Square Brush',
    category: 'smear',
    description: 'Flat geometric smudge tool for structured blending',
    profile: 'ribbon',
    materialType: 'watercolor',
    defaultSize: 0.055,
    defaultOpacity: 0.50,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#444444',
    iconFile: 'palette_smudge_soft_flat_brush.png'
  },
  smudge_coarse: {
    id: 'smudge_coarse',
    name: 'Smudge Coarse Angular',
    category: 'smear',
    description: 'Textured coarse angular smudge tool from official Smudge set',
    profile: 'bristle',
    materialType: 'watercolor',
    defaultSize: 0.060,
    defaultOpacity: 0.45,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: true,
    colorHex: '#555555',
    iconFile: 'palette_smudge_coarse_angular_brush.png'
  },

  // -------------------------------------------------------------
  // 8. ANIMATED & MAGIC MATERIALS
  // -------------------------------------------------------------
  waterfall_stream: {
    id: 'waterfall_stream',
    name: 'Waterfall Stream',
    category: 'animated',
    description: 'Animated toon waterfall with flowing noise layers and highlights',
    profile: 'ribbon',
    materialType: 'waterfall',
    defaultSize: 0.060,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#1d9fd6',
    iconFile: 'Wash.png'
  },
  caustic_light: {
    id: 'caustic_light',
    name: 'Caustic Light',
    category: 'animated',
    description: 'Animated underwater caustic light beams via smooth Voronoi',
    profile: 'ribbon',
    materialType: 'caustic',
    defaultSize: 0.070,
    defaultOpacity: 0.90,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#1ca8b8',
    iconFile: 'glowneon.png'
  },
  foam_lattice: {
    id: 'foam_lattice',
    name: 'Foam Lattice',
    category: 'animated',
    description: 'Cel-shaded animated foam bubbles via dual opposing FBM noise',
    profile: 'ribbon',
    materialType: 'foam',
    defaultSize: 0.065,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#2488aa',
    iconFile: 'blurry.png'
  },
  ripple_strand: {
    id: 'ripple_strand',
    name: 'Ripple Strand',
    category: 'animated',
    description: 'Stylized flowing ripple with sinusoidal wave crests',
    profile: 'ribbon',
    materialType: 'ripple',
    defaultSize: 0.055,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#3078a0',
    iconFile: 'Wash.png'
  },
  rainbow_ribbon: {
    id: 'rainbow_ribbon',
    name: 'Rainbow Ribbon',
    category: 'animated',
    description: 'Animated scrolling rainbow gradient with shimmering noise',
    profile: 'ribbon',
    materialType: 'rainbow_scroll',
    defaultSize: 0.055,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.40,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ffffff',
    iconFile: 'glowbrush.png'
  },
  sparkle_trail: {
    id: 'sparkle_trail',
    name: 'Sparkle Trail',
    category: 'animated',
    description: 'Animated twinkling starburst sparkles with glowing rays',
    profile: 'ribbon',
    materialType: 'sparkle',
    defaultSize: 0.060,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ffd700',
    iconFile: 'sparkle.png'
  },
  lava_flow: {
    id: 'lava_flow',
    name: 'Lava Flow',
    category: 'animated',
    description: 'Animated bubbling molten magma and incandescent glow',
    profile: 'tube',
    materialType: 'lava',
    defaultSize: 0.065,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#ff4500',
    iconFile: 'Wispy.png'
  },
  galaxy_swirl: {
    id: 'galaxy_swirl',
    name: 'Galaxy Swirl',
    category: 'animated',
    description: 'Deep cosmic nebula with sharp twinkling star cluster grid',
    profile: 'ribbon',
    materialType: 'galaxy',
    defaultSize: 0.070,
    defaultOpacity: 1.0,
    smoothingAlpha: 0.35,
    taperStart: true,
    taperEnd: true,
    pressureRadius: true,
    pressureOpacity: false,
    colorHex: '#6a0dad',
    iconFile: 'blurry.png'
  }
};
